/*!
*   Verified Relationship Credentials (VRC)
*/

use affinidi_data_integrity::DataIntegrityProof;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Verifiable Relationship Credential Specification
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct VRC {
    /// JSON-LD links to contexts
    /// Must contain at least:
    /// https://www.w3.org/ns/credentials/v2
    /// https://firstperson.network/credentials/relationship/v1
    #[serde(rename = "@context")]
    pub context: Vec<String>,

    /// Credential type identifiers
    /// Must contain at least:
    /// VerifiableCredential
    /// RelationshipCredential
    #[serde(rename = "type")]
    pub type_: Vec<String>,

    /// DID of the entity issuing this credential
    pub issuer: String,

    /// ISO 8601 format of when this credentials become valid from
    pub valid_from: DateTime<Utc>,

    /// Human-readable name or title of this relationship
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    /// Human-readable description of the credential or the relationship
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,

    /// The relationship assertion between the entities involved
    pub credential_subject: CredentialSubject,

    /// Optional: URI or term from a published vocabulary specifying the nature of the relationship
    #[serde(skip_serializing_if = "Option::is_none")]
    pub relationship_type: Option<String>,

    /// Optional: Start date of the relationship, in ISO 8601 format
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start_date: Option<DateTime<Utc>>,

    /// Optional: End date of the relationship, if applicable, in ISO 8601 format
    #[serde(skip_serializing_if = "Option::is_none")]
    pub end_date: Option<DateTime<Utc>>,

    /// Optional: Describes the live witnessing session linking the Fair Witness and the participants, if any
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session: Option<Session>,

    /// Cryptographic proof of credential authenticity
    pub proof: Option<DataIntegrityProof>,
}

impl Default for VRC {
    fn default() -> Self {
        VRC {
            context: vec![
                "https://www.w3.org/ns/credentials/v2".to_string(),
                "https://firstperson.network/credentials/relationship/v1".to_string(),
            ],
            type_: vec![
                "VerifiableCredential".to_string(),
                "RelationshipCredential".to_string(),
            ],
            issuer: String::new(),
            valid_from: Utc::now(),
            name: None,
            description: None,
            credential_subject: CredentialSubject::default(),
            relationship_type: None,
            start_date: None,
            end_date: None,
            session: None,
            proof: None,
        }
    }
}

/// The relationship assertion between the entities involved
#[derive(Default, Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct CredentialSubject {
    /// Information about the asserting ("from") entity
    pub from: FromSubject,

    /// Information about the target ("to") entity
    pub to: ToSubject,
}

/// Information about the asserting ("from") entity
#[derive(Default, Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct FromSubject {
    /// DID of the "from" entity
    pub did: String,

    /// Human-readable name of the "from" entity
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    /// Array of verifiable, subject-controlled identifiers/personas (such as DIDs or resolvable URIs) for trustworthy correlation across decentralized identity systems
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub also_known_as: Vec<String>,

    /// Optional: An array of cryptographic proofs, each generated by signing a
    /// canonical message (such as the subject's DID or a credential hash) with
    /// the private key of an identifier listed in alsoKnownAs. Used to demonstrate
    /// that the entity controls the referenced identifier.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub linkage_proofs: Vec<LinkageProof>,

    /// Optional: An array of references to externally published proofs or
    /// verifiable credentials that demonstrate the entity’s control over an
    /// identifier in alsoKnownAs
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub external_proofs: Vec<ExternalProof>,
}

/// An array of cryptographic proofs, each generated by signing a canonical message
/// (such as the subject's DID or a credential hash) with the private key of an
/// identifier listed in alsoKnownAs. Used to demonstrate that the entity controls
/// the referenced identifier.
#[derive(Default, Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct LinkageProof {
    /// The proof or signature type (e.g., "Ed25519Signature2020", "PGPSignature2020")
    #[serde(rename = "type")]
    pub type_: String,

    /// The identifier (from alsoKnownAs) for which control is being proven
    pub identifier: String,

    /// The ISO 8601 date and time when the proof was created
    pub created: DateTime<Utc>,

    /// The cryptographic signature value, such as a JWS or PGP armored block,
    /// demonstrating control of the identifier
    pub proof_value: String,

    /// A unique nonce that used when coordinating an exchange session
    #[serde(skip_serializing_if = "Option::is_none")]
    pub nonce: Option<String>,
}

/// An array of references to externally published proofs or verifiable credentials
/// that demonstrate the entity’s control over an identifier in alsoKnownAs
#[derive(Default, Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct ExternalProof {
    /// The identifier (from alsoKnownAs) to which the external proof refers
    pub identifier: String,

    /// A HTTPS URL, DID URL, or other resolvable URI where the verifiable proof
    /// can be found
    pub proof_url: String,

    /// The type or standard of the external proof
    /// (e.g., "VerifiableCredential", "LinkedDataSignature2020", "PGPSignature2020")
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub type_: Option<String>,

    /// The ISO 8601 date and time when the external proof was created.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created: Option<DateTime<Utc>>,
}

/// Information about the target ("to") entity
#[derive(Default, Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct ToSubject {
    /// DID of the "to" entity
    pub did: String,

    /// Human-readable name of the "to" entity
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    /// Optional: Array of verifiable, subject-controlled identifiers/personas
    /// (such as DIDs or resolvable URIs) for trustworthy correlation across
    /// decentralized identity systems
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub also_known_as: Vec<String>,
}

/// Describes the live witnessing session linking the Fair Witness and the
/// participants, if any
#[derive(Default, Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Session {
    /// A unique session identifier (e.g. UUID or URN)
    pub id: String,

    /// Optional: The DID of the session witness of any
    #[serde(skip_serializing_if = "Option::is_none")]
    pub witness_id: Option<String>,
}
